--! Previous: -
--! Hash: sha1:a83ef742fb21ce54c862540a1b9f6808723cf40b

CREATE SCHEMA IF NOT EXISTS tenant;

-- ---------------------------------------------------------------------------
-- Tenants
-- ---------------------------------------------------------------------------

-- Core tenant record. PK is a UUIDv7 (time-ordered) generated by the
-- built-in uuidv7() function available in PostgreSQL 18+.

CREATE TABLE tenant.tenants (
  id          UUID PRIMARY KEY DEFAULT uuidv7(),
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Tenant Identity Providers
-- ---------------------------------------------------------------------------

-- 1:1 with tenant.tenants (shared PK). Stores the OIDC / JWT configuration
-- the API gateway uses to validate tokens for this tenant.

CREATE TABLE tenant.tenant_idps (
  tenant_id  UUID PRIMARY KEY REFERENCES tenant.tenants(id) ON DELETE CASCADE,
  jwks_uri   TEXT NOT NULL,
  jwt_iss    TEXT NOT NULL,
  jwt_aud    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup by (iss, aud) — used by private.as_user_oidc() on every request.
CREATE UNIQUE INDEX idx_tenant_idps_iss_aud ON tenant.tenant_idps (jwt_iss, jwt_aud);
